### ISSUE TITLE
[ctrl]+u sometimes opens chrome sourceview instead of trigger main quickaction

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1178]
### Type of issue
Bug
### Current behavior
Sometimes the usage of [ctrl]+u leads to chrome source view instead of triggering the main quick-action. Mostly happens when the focus is on number fields. If the focus is on a list field or button, then the quick-action is triggered.
### Expected behavior
[ctrl]+u Shall trigger the main action.
### Steps to reproduce
Open window window/540196.
Select a top-level line. Press [ctrl]+u. Works.
In modal overlay, the first line is selected per default. press [tab] once, then [ctrl]+u: the source-view opens. Try the same with tabbing to first list field. Then the action trigger is done.

**Comment by metas-lc** [comment]
IT
still happens for me:
1. went to receipt candidates https://w101.metasfresh.com:8443/window/540196?page=1&viewId=540196-d2a5e4a3e98e4e7f97ff5b2341370c89
2. selected a line, pressed ctrl +u => hu editor opens
3. press tab once => you can see the cursor on the first weight
4. press ctrl+u again
=> view source opened NOK

**Comment by metas-lc** [comment]
IT

1. open receipt candidates https://w101.metasfresh.com:8443/window/540196?page=1&viewId=540196-d2a5e4a3e98e4e7f97ff5b2341370c89
2. selected a line, pressed ctrl +u => hu editor opens
3. press tab once => you can see the cursor on the first weight
4. press ctrl+u again
=> main quickaction is triggered (create material receipt) OK
=> error
:"Internal Server Error" 
exception:"org.adempiere.exceptions.AdempiereException"
message:"saveUpdate failed"
path:"/rest/api/process/ADP_540750/1006964/start" 
NOK
=>  error
error:"Not Found"
exception:"de.metas.ui.web.exceptions.EntityNotFoundException"
message:"No document found for rowId=1000142"
path:"/rest/api/documentView/540189/540189-262c052d63294c8bb5fc5664b53cbe95/1000142/layout" 
NOK
=> no receipt was created
note: there are 2 process that start: one from window behind the modal, and one from the modal

**Comment by teosarca** [comment]
note to backend devs. Might be that we have to check.
One of the processes are throwing following exception. Might be that's because it's called twice?!
```
2017-10-20 10:39:45.008 ERROR 25181 [                ][          ] --- [http-nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.adempiere.exceptions.AdempiereException: saveUpdate failed] with root cause

org.adempiere.exceptions.AdempiereException: saveUpdate failed
        at org.compiere.model.PO.save0(PO.java:2876)
        at org.compiere.model.PO.access$100(PO.java:137)
        at org.compiere.model.PO$1.run(PO.java:2767)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:771)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:683)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:584)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:515)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:500)
        at org.compiere.model.PO.saveEx(PO.java:2760)
        at org.adempiere.model.POWrapper.save(POWrapper.java:787)
        at org.adempiere.model.InterfaceWrapperHelper.save(InterfaceWrapperHelper.java:541)
        at de.metas.inoutcandidate.spi.impl.InOutProducerFromReceiptScheduleHU.unassignHU(InOutProducerFromReceiptScheduleHU.java:773)
        at de.metas.inoutcandidate.spi.impl.InOutProducerFromReceiptScheduleHU.transferHandlingUnits(InOutProducerFromReceiptScheduleHU.java:634)
        at de.metas.inoutcandidate.spi.impl.InOutProducerFromReceiptScheduleHU.createReceiptLines(InOutProducerFromReceiptScheduleHU.java:234)
        at de.metas.inoutcandidate.spi.impl.InOutProducerFromReceiptScheduleHU.createCurrentReceiptLines(InOutProducerFromReceiptScheduleHU.java:197)
        at de.metas.inoutcandidate.api.impl.InOutProducer.process(InOutProducer.java:170)
        at de.metas.inoutcandidate.api.impl.InOutProducer.process(InOutProducer.java:69)
        at org.adempiere.ad.trx.processor.api.impl.TrxItemChunkProcessorExecutor.processItem(TrxItemChunkProcessorExecutor.java:260)
        at org.adempiere.ad.trx.processor.api.impl.TrxItemChunkProcessorExecutor.execute(TrxItemChunkProcessorExecutor.java:157)
        at de.metas.handlingunits.receiptschedule.impl.HUReceiptScheduleBL.processReceiptSchedules0(HUReceiptScheduleBL.java:370)
        at de.metas.handlingunits.receiptschedule.impl.HUReceiptScheduleBL.lambda$processReceiptSchedules$0(HUReceiptScheduleBL.java:290)
        at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:771)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:683)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:584)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:515)
        at de.metas.handlingunits.receiptschedule.impl.HUReceiptScheduleBL.processReceiptSchedules(HUReceiptScheduleBL.java:290)
        at de.metas.ui.web.handlingunits.process.WEBUI_M_HU_CreateMaterialReceipt.doIt(WEBUI_M_HU_CreateMaterialReceipt.java:96)
        at de.metas.process.JavaProcess.startProcess(JavaProcess.java:271)
        at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:563)
        at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:459)
        at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:49)
        at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:223)
        at org.adempiere.ad.trx.api.impl.AbstractTrxManager.runOutOfTransaction(AbstractTrxManager.java:923)
        at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:281)
        at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:170)
        at de.metas.process.ProcessExecutor.access$1100(ProcessExecutor.java:49)
        at de.metas.process.ProcessExecutor$Builder.executeSync(ProcessExecutor.java:653)
        at de.metas.ui.web.process.adprocess.ADProcessInstanceController.executeADProcess(ADProcessInstanceController.java:312)
        at de.metas.ui.web.process.adprocess.ADProcessInstanceController.startProcess(ADProcessInstanceController.java:287)
        at de.metas.ui.web.process.ProcessRestController.lambda$null$8(ProcessRestController.java:255)
        at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.forProcessInstanceWritable(ADProcessInstancesRepository.java:384)
        at de.metas.ui.web.process.ProcessRestController.lambda$startProcess$9(ProcessRestController.java:254)
        at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)
        at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)
        at de.metas.ui.web.process.ProcessRestController.startProcess(ProcessRestController.java:252)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
```

**Comment by metas-mk** [comment]
@PabloSichert 
Checked on current master w101. The Problem still occurs. Her a case when createing a new Sales Order and line and the completing w/ [ctrl]+u.

![image](https://user-images.githubusercontent.com/13365687/32440390-3ed73cae-c2f3-11e7-98ff-10bf43805bcb.png)

**Comment by metas-ts** [comment]
FYI, I briefly checked the situaion in the sales and purchase order window, after the lastest fix.
there it's not working yet. I.e. instead of completing the current order, it opens the source view

**Comment by teosarca** [comment]
I think tihs is no longer an issue after https://github.com/metasfresh/metasfresh-webui-frontend/issues/1283

where we changed the CTRL+ to ALT+.

wdyt?

**Comment by metas-mk** [comment]
Yepp. Works with alt+enter. Closing.

**Comment by PabloSichert** [comment]
@teosarca the two issues should now be fixed independently - so it should work, even if the shortcut still was `Control+U`
