### ISSUE TITLE
Error when maximize subtab which does not support quick input

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1286]
### Is this a bug or feature request?
Bug
### What is the current behavior?
![image](https://user-images.githubusercontent.com/15378036/31817392-699bbb90-b59c-11e7-9914-1f7209c62581.png)
The tab is maximized, but we get this error:
```
de.metas.ui.web.exceptions.EntityNotFoundException: Batch input not available
	at de.metas.ui.web.quickinput.QuickInputDescriptorFactoryService.getQuickInputEntityDescriptor(QuickInputDescriptorFactoryService.java:113)
	at de.metas.ui.web.quickinput.QuickInputDescriptorFactoryService.getQuickInputEntityDescriptor(QuickInputDescriptorFactoryService.java:58)
	at de.metas.ui.web.quickinput.WindowQuickInputRestController.lambda$1(WindowQuickInputRestController.java:167)
	at de.metas.ui.web.window.model.DocumentCollection.forRootDocumentReadonly(DocumentCollection.java:219)
	at de.metas.ui.web.quickinput.WindowQuickInputRestController.lambda$0(WindowQuickInputRestController.java:161)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$4.call(TrxCallableWrappers.java:193)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:771)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:683)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:584)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:515)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:492)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:469)
	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$0(Execution.java:194)
	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$2(Execution.java:237)
	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)
```
#### Which are the steps to reproduce?
* Open partner
* Go to tab User and press when maximize icon

**Comment by teosarca** [comment]
i.e.
![image](https://user-images.githubusercontent.com/1244701/31817742-f11cd472-b59d-11e7-941c-1a6201a4bf54.png)

![image](https://user-images.githubusercontent.com/1244701/31817794-1ebaadbe-b59e-11e7-9ce3-2a123d98986f.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* maximize subtab which does not support quick input: no error, working fine: OK
