### ISSUE TITLE
Error when opening HU Editor window / selecting a HU in picking tray clearing

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1801]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When opening HU Editor window (window/540189), i got

```
Error: For input string: "[object...
Server error
For input string: "[object Object]"

{timestamp: 1526993588371, status: 500, error: "Internal Server Error",…}
error
:
"Internal Server Error"
exception
:
"java.lang.NumberFormatException"
message
:
"For input string: "[object Object]""
path
:
"/rest/api/documentView/packingHUs/packingHUs-CK-2156425-2205175/quickActions"
status
:
500
timestamp
:
1526993588371
trace
:
["java.lang.NumberFormatException: For input string: "[object Object]"",…]
[0 … 99]
0
:
"java.lang.NumberFormatException: For input string: "[object Object]""
1
:
"	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)"
2
:
"	at java.lang.Integer.parseInt(Integer.java:580)"
3
:
"	at java.lang.Integer.parseInt(Integer.java:615)"
4
:
"	at de.metas.ui.web.handlingunits.HUEditorRowId.fromJson(HUEditorRowId.java:110)"
5
:
"	at de.metas.ui.web.handlingunits.HUEditorRowId.ofDocumentId(HUEditorRowId.java:77)"
6
:
"	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)"
7
:
"	at java.util.Iterator.forEachRemaining(Iterator.java:116)"
8
:
"	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)"
9
:
"	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)"
10
:
"	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)"
11
:
"	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)"
12
:
"	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)"
13
:
"	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)"
14
:
"	at de.metas.ui.web.window.datatypes.DocumentIdsSelection.toSet(DocumentIdsSelection.java:277)"
15
:
"	at de.metas.ui.web.handlingunits.HUEditorRowFilter$Builder.onlyRowIdsFromSelection(HUEditorRowFilter.java:88)"
16
:
"	at de.metas.ui.web.handlingunits.HUEditorRowFilter.onlyRowIds(HUEditorRowFilter.java:56)"
17
:
"	at de.metas.ui.web.handlingunits.HUEditorView.streamByIds(HUEditorView.java:408)"
18
:
"	at de.metas.ui.web.handlingunits.report.HUReportProcessInstancesRepository.checkApplies(HUReportProcessInstancesRepository.java:194)"
19
:
"	at de.metas.ui.web.handlingunits.report.HUReportProcessInstancesRepository.lambda$streamDocumentRelatedProcesses$0(HUReportProcessInstancesRepository.java:181)"
20
:
"	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)"
21
:
"	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)"
22
:
"	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)"
23
:
"	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)"
24
:
"	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)"
25
:
"	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)"
26
:
"	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)"
27
:
"	at com.google.common.collect.CollectSpliterators$1WithCharacteristics.forEachRemaining(CollectSpliterators.java:65)"
28
:
"	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)"
29
:
"	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)"
30
:
"	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)"
31
:
"	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)"
32
:
"	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)"
33
:
"	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)"
34
:
"	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)"
35
:
"	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3566)"
36
:
"	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)"
37
:
"	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)"
38
:
"	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)"
39
:
"	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)"
40
:
"	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)"
41
:
"	at de.metas.ui.web.view.ViewRestController.getDocumentQuickActions(ViewRestController.java:386)"
42
:
"	at sun.reflect.GeneratedMethodAccessor259.invoke(Unknown Source)"
43
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
44
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
45
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
46
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
47
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
48
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
49
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
50
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
51
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
52
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
53
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
54
:
"	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
55
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
56
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
57
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
58
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
59
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
60
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
61
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
62
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
63
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
64
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
65
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
66
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
67
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
68
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
69
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
70
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
71
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
72
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
73
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
74
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
75
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
76
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
77
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
78
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
79
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
80
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
81
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
82
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
83
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
84
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
85
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
86
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
87
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
88
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
89
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
90
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
91
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
92
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
93
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
94
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
95
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
96
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
97
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
98
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
99
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
[100 … 120]
100
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
101
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
102
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
103
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
104
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
105
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
106
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
107
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
108
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
109
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
110
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
111
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
112
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
113
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
114
:
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
115
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
116
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
117
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
118
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
119
:
"	at java.lang.Thread.run(Thread.java:748)"
120
:
""
```

it also happened when i selected a HU in picking tray clearing (window/540371), on the left side.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
No error.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

got no error anymore, in both cases (HU Editor window and Picking Tray Clearing Terminal): OK
